"""Initial migration

Revision ID: 7937f1cf6fdf
Revises: 
Create Date: 2026-02-01 22:05:44.246355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7937f1cf6fdf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('variant_sku', sa.String(), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('variant_id')
    )
    op.create_index(op.f('ix_inventory_variant_sku'), 'inventory', ['variant_sku'], unique=False)
    op.create_table('inventory_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("event_type IN ('RESERVED', 'RELEASED', 'CONFIRMED', 'STOCK_ADDED')", name='check_event_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_events_timestamp'), 'inventory_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_inventory_events_variant_id'), 'inventory_events', ['variant_id'], unique=False)
    op.create_table('inventory_reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('ACTIVE', 'RELEASED', 'CONFIRMED')", name='check_reservation_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_reservations_order_id'), 'inventory_reservations', ['order_id'], unique=False)
    op.create_index(op.f('ix_inventory_reservations_variant_id'), 'inventory_reservations', ['variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_reservations_variant_id'), table_name='inventory_reservations')
    op.drop_index(op.f('ix_inventory_reservations_order_id'), table_name='inventory_reservations')
    op.drop_table('inventory_reservations')
    op.drop_index(op.f('ix_inventory_events_variant_id'), table_name='inventory_events')
    op.drop_index(op.f('ix_inventory_events_timestamp'), table_name='inventory_events')
    op.drop_table('inventory_events')
    op.drop_index(op.f('ix_inventory_variant_sku'), table_name='inventory')
    op.drop_table('inventory')
    # ### end Alembic commands ###
